Repository gelilaa/VoxBox, pull requests merged in 2021-01, with the labels that each got.

#64 Backend user
  api/middleware/withAuth.js
  api/models/Post.js
  api/models/User.js
  api/routes/posts.js
  api/routes/signin.js
  api/routes/users.js
  api/server.js
  client/public/user.png
Labels: Back-End

#68 Comment route
  .vscode/launch.json
  api/models/Post.js
  api/routes/comments.js
  api/routes/posts.js
  api/server.js
Labels: Back-End

#80 Comment button
  client/src/components/newsfeed/Card.jsx
  client/src/components/newsfeed/Cards.jsx
  client/src/components/newsfeed/NewsfeedHeader.jsx
  client/src/components/newsfeed/newsfeed.css
  client/src/components/profile/Comment.jsx
  client/src/components/profile/Help.jsx
  client/src/components/profile/HelpDetails.jsx
  client/src/components/profile/NewComment.js
  client/src/components/profile/Profile.css
Labels: Front-End

#96 Token exp fix
  api/models/User.js
  api/server.js
  client/src/App.js
  client/src/components/auth/signin.jsx
  client/src/components/auth/tokenExp.jsx
  client/src/components/newsfeed/Cards.jsx
  client/src/components/newsfeed/createPost.jsx
  client/src/components/profile/Bio.jsx
  client/src/components/profile/Comment.jsx
  client/src/components/profile/HelpDetails.jsx
  client/src/components/profile/Profile.jsx
  client/src/store/actions/loginActions.js
Labels: Back-End, bug

#107 All css fixes
  api/routes/posts.js
  client/src/components/auth/verifyEmail.jsx
  client/src/components/backlink/Backlink.css
  client/src/components/footer/Footer.css
  client/src/components/footer/Footer.jsx
  client/src/components/homepage/Cta.jsx
  client/src/components/navbar/signedOut.jsx
  client/src/components/newsfeed/Card.jsx
  client/src/components/newsfeed/Newsfeed.jsx
  client/src/components/newsfeed/NewsfeedHeader.jsx
  client/src/components/newsfeed/SearchBar.jsx
  client/src/components/newsfeed/createPost.jsx
  client/src/components/newsfeed/newsfeed.css
  client/src/components/profile/Bio.jsx
  client/src/components/profile/HelpDetails.jsx
  client/src/components/profile/Profile.css
  client/src/components/profile/ProfileDetails.jsx
Labels: Front-End, bug

#111 added back button and edit button disabled when clicked
  client/src/components/backlink/Backlink.css
  client/src/components/backlink/Backlink.jsx
  client/src/components/profile/Bio.jsx
  client/src/components/profile/Comment.jsx
  client/src/components/profile/Help.jsx
  client/src/components/profile/HelpDetails.jsx
  client/src/components/profile/NewComment.js
  client/src/components/profile/Profile.css
  client/src/components/profile/Profile.jsx
  client/src/components/profile/ProfileDetails.jsx
Labels: Front-End

#118 finishing touches for heroku
  api/routes/posts.js
  client/src/components/backlink/Backlink.css
  client/src/components/backlink/Backlink.jsx
  client/src/components/newsfeed/Card.jsx
  client/src/components/newsfeed/createPost.jsx
  client/src/components/profile/Bio.jsx
  client/src/components/profile/Comment.jsx
  client/src/components/profile/Help.jsx
  client/src/components/profile/HelpDetails.jsx
  client/src/components/profile/NewComment.js
  client/src/components/profile/Profile.css
  client/src/components/profile/Profile.jsx
  client/src/components/profile/ProfileDetails.jsx
Labels: heroku-problem
